name = "h2-multi"
url = "https://127.0.0.1:4444/multi.html"
iterations = 20
user_agent = "Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36"
viewport = [824, 1830]
device_pixel_ratio = 2.625
servoshell_args = ["--ignore-certificate-errors"]

[fixture]
kind = "http2"
port = 4444
doc_root = "www"
