//! Rust types generated by `prost-build` from `proto/perfetto_trace.proto`.
//!
//! The generated file is placed in `$OUT_DIR/perfetto.protos.rs` (package
//! name from the .proto file is `perfetto.protos`). We `include!` it here
//! and re-export the messages we use under a stable path.

#[allow(clippy::all)]
pub mod perfetto_protos {
    include!(concat!(env!("OUT_DIR"), "/perfetto.protos.rs"));
}

#[allow(unused_imports)]
pub use perfetto_protos::{
    InternedData, ProcessDescriptor, ThreadDescriptor, TracePacket, TrackDescriptor, TrackEvent,
};
